MicraftSolutions/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BusinessLayer;
using System.IO;
using System.Data;
using System.Data.OleDb;

namespace MicraftSolutions.Controllers
{
    public class OrdersController : Controller
    {
        Business objBusiness = new Business();

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAllOrders()
        {
            List<OrdersModel> lstOrders = new List<OrdersModel>();
            try
            {
                lstOrders = objBusiness.GetAllOrders();
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(lstOrders, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int orderId)
        {
            List<OrderDetailsModel> lstOrderDetails = new List<OrderDetailsModel>();
            try
            {
                lstOrderDetails = objBusiness.GetOrdersDetailsById(orderId);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View(lstOrderDetails);
        }

        [HttpGet]
        public ActionResult AddNewOrder()
        {
            List<CustomerModel> lstCust = new List<CustomerModel>();
            List<ProductModel> lstProd = new List<ProductModel>();
            try
            {
                lstCust = objBusiness.GetAllCustomers();

                ViewBag.Customers = lstCust;

                lstProd = objBusiness.GetAllProducts();

                ViewBag.Products = lstProd;
            }
            catch (Exception ex)
            {
                throw ex;
            }

            return View();
        }

        [HttpPost]
        public bool SubmitNewOrder(NewOrderModel data)
        {
            Boolean result = false;
            try
            {
                int orderId = 0;
                orderId = objBusiness.AddOrderAndDetails(data);

                if (orderId > 0)
                {
                    result = true;
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return result;
        }

        public JsonResult GetOrdersDetailsById(int orderId)
        {
            List<OrderDetailsModel> lstOrdersDetails = new List<OrderDetailsModel>();
            try
            {
                lstOrdersDetails = objBusiness.GetOrdersDetailsById(orderId);
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(lstOrdersDetails, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Edit(int orderId)
        {
            List<CustomerModel> lstCust = new List<CustomerModel>();
            List<ProductModel> lstProd = new List<ProductModel>();

            try
            {
                lstCust = objBusiness.GetAllCustomers();

                ViewBag.Customers = lstCust;

                lstProd = objBusiness.GetAllProducts();

                ViewBag.Products = lstProd;

                TempData["orderId"] = orderId;
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return View();
        }



        public ActionResult ImportExcel(int custId, int orderId)
        {
            TempData["CustomerId"] = custId;

            TempData["orderId"] = orderId;


            return View();
        }


        [HttpPost]
        public ActionResult Importexcel()
        {
            NewOrderModel objNewOrder = new NewOrderModel();
            int custId = 0;
            int orderId = 0;
            try
            {
                custId = Convert.ToInt32(TempData["CustomerId"]);
                orderId = Convert.ToInt32(TempData["orderId"]);

                objNewOrder.OrderID = orderId;

                if (custId > 0)
                {
                    objNewOrder.CustomerID = custId;

                    DataTable dt = new DataTable();

                    if (Request.Files["FileUpload1"].ContentLength > 0)
                    {
                        string extension = System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName).ToLower();
                        string query = null;
                        string connString = "";

                        string[] validFileTypes = { ".xls", ".xlsx", ".csv" };

                        string path1 = string.Format("{0}/{1}", Server.MapPath("~/Content/Uploads"), Request.Files["FileUpload1"].FileName);
                        if (!Directory.Exists(path1))
                        {
                            Directory.CreateDirectory(Server.MapPath("~/Content/Uploads"));
                        }
                        if (validFileTypes.Contains(extension))
                        {
                            if (System.IO.File.Exists(path1))
                            {
                                System.IO.File.Delete(path1);
                            }
                            Request.Files["FileUpload1"].SaveAs(path1);

                            //Connection String to Excel Workbook  
                            if (extension.Trim() == ".xls")
                            {
                                connString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + path1 + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                                dt = ConvertXSLXtoDataTable(path1, connString);
                                ViewBag.Data = dt;
                            }
                            else if (extension.Trim() == ".xlsx")
                            {
                                connString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + path1 + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                                dt = ConvertXSLXtoDataTable(path1, connString);
                                ViewBag.Data = dt;
                            }
                            else if (extension == ".csv")
                            {
                                dt = ConvertCSVtoDataTable(path1);
                                ViewBag.Data = dt;
                            }

                            if (dt != null && dt.Rows.Count > 1)
                            {
                                List<OrderDetailsModel> lstOrderDetails = new List<OrderDetailsModel>();
                                for (int i = 0; i < dt.Rows.Count; i++)
                                {
                                    OrderDetailsModel objOrderDetails = new OrderDetailsModel();

                                    objOrderDetails.ProductCode = Convert.ToString(dt.Rows[i][0]);
                                    objOrderDetails.Qty = Convert.ToInt32(dt.Rows[i][1]);

                                    ProductModel objProduct = new ProductModel();

                                    objProduct = objBusiness.GetProductByCode(objOrderDetails.ProductCode);

                                    if (objProduct != null)
                                    {
                                        objOrderDetails.Amount = objProduct.Rate * objOrderDetails.Qty;

                                        objNewOrder.TotalAmount = objNewOrder.TotalAmount + objOrderDetails.Amount;

                                        objNewOrder.TotalQty = objNewOrder.TotalQty + objOrderDetails.Qty;

                                        lstOrderDetails.Add(objOrderDetails);
                                    }

                                }

                                objNewOrder.lstOrderDetails = lstOrderDetails;


                                if (objNewOrder.lstOrderDetails != null)
                                {
                                    orderId = objBusiness.AddOrderAndDetails(objNewOrder);

                                    if (orderId > 0)
                                    {
                                        ViewBag.Result = "Success: Excel Uploaded Successfully!";

                                        // Source file to be renamed  
                                        string sourceFile = path1;
                                        // Create a FileInfo  
                                        System.IO.FileInfo fi = new System.IO.FileInfo(sourceFile);
                                        // Check if file is there  
                                        if (fi.Exists)
                                        {
                                            string fileName = "OrderID_" + orderId + System.IO.Path.GetExtension(Request.Files["FileUpload1"].FileName).ToLower();

                                            string newFilePath = Server.MapPath("~/Content/Uploads/") + fileName;

                                            if (System.IO.File.Exists(newFilePath))
                                            {
                                                System.IO.File.Delete(newFilePath);

                                            }

                                            fi.MoveTo(Server.MapPath("~/Content/Uploads/") + fileName);

                                        }
                                    }
                                    else
                                    {
                                        ViewBag.Error = "Failure: Something went wrong while uploading.";
                                    }
                                }


                            }

                        }
                        else
                        {
                            ViewBag.Error = "Please Upload Files in .xls, .xlsx or .csv format";
                        }
                    }
                }
                else
                {
                    ViewBag.Error = "Something went wrong";

MicraftSolutions/Views/Orders/AddNewOrder.cshtml
@{
    ViewBag.Title = "AddNewOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }
    /* Zebra striping */
    tr:nth-of-type(odd) {
        background: #eee;
    }

    th {
        background: #333;
        color: white;
        font-weight: bold;
    }

    td, th {
        padding: 6px;
        border: 1px solid #ccc;
        text-align: left;
    }

    /*th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }*/
</style>



<h2 style="text-align:center">Add New Order</h2>

<div class="form-horizontal">

    <form id="AddProductForm">
        <div class="form-group">
            @Html.Label("Customer Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CustomerID", new SelectList(ViewBag.Customers, "ID", "Name"), "Please select", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Product Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductCode", new SelectList(ViewBag.Products, "ProductCode", "ProductName"), "Please select", new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.Label("Quantity", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="Qty" name="Qty" type="text" class="form-control" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2"></div>

            <div class="col-md-10">
                <input id="btnAddProduct" type="button" value="Add Product" class="btn btn-success " />
            </div>
        </div>

    </form>


    <div class="form-group">
        @Html.Label("or Upload Excel", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <button class="btn btn-primary" id="btnUpload">Upload</button>
        </div>
    </div>

    <table id="tblProductsInOrder" style="display:none">
        <thead>
            <tr>
                <th style="display:none">Product Code</th>
                <th>Product Name</th>
                <th>Product Image</th>
                <th>Unit</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Amount</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>

    <div>
        <span style="text-align:right">
            <p>Total Quantity:</p>
            <p id="tQty">0</p>

            <p>Total Amount:</p>
            <p id="tAmt">0.00</p>
        </span>
    </div>

    <br />

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnPlaceOrder" type="button" value="Place this order" class="btn btn-primary pull-right" />
        </div>
    </div>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("#btnAddProduct").click(function () {
            var validForm = false;

            validForm = $("#AddProductForm").valid();


            if (validForm) {
                var pCode = $("#ProductCode").val();
                var pQty = $("#Qty").val();

                $.ajax({
                    type: "GET",
                    url: "http://localhost:53405/Product/GetProductByCode?pCode=" + pCode,
                    cache: false,
                    success: function (data) {
                        //alert(JSON.stringify(data));
                        //$('#tblProductsInOrder tbody').empty();

                        var isProductFound = false;

                        $('#tblProductsInOrder .tdPCode').each(function () {
                            //var thisQty = $(this).find(".tdQty").html()
                            thisPCode = $(this).html();

                            if (pCode == thisPCode) {
                                var thisQty = parseInt($(this).closest('tr').find(".tdQty").html());
                                var thisAmt = parseInt($(this).closest('tr').find(".tdAmt").html());

                                $(this).closest('tr').find(".tdQty").html(parseInt(thisQty) + parseInt(pQty));

                                var updatedQty = parseInt($(this).closest('tr').find(".tdQty").html());

                                $(this).closest('tr').find(".tdAmt").html(parseFloat(parseInt(updatedQty) * parseFloat(data.Rate)));

                                var updatedAmt = parseInt($(this).closest('tr').find(".tdAmt").html());

                                //Total Quantity
                                var tQty = parseInt($("#tQty").html());
                                tQty = parseInt(tQty - parseInt(thisQty));
                                tQty = parseInt(tQty) + parseInt(updatedQty);
                                $("#tQty").html(tQty);


                                //Total Amount
                                var tAmt = parseFloat($("#tAmt").html());
                                tAmt = parseFloat(tAmt - parseFloat(thisAmt));
                                tAmt = parseFloat(tAmt + parseFloat(updatedAmt));
                                $("#tAmt").html(tAmt);


                                isProductFound = true;
                            }

                            //tQty = tQty + parseInt(thisQty);
                        });

                        if (!isProductFound) {

                            var tr;

                            tr = $('<tr/>');

                            tr.append("<td class='tdPCode' style='display:none'>" + data.ProductCode + "</td>");
                            tr.append("<td>" + data.ProductName + "</td>");
                            tr.append("<td> <img class='imgProduct' src='" + data.ProductImage + "'></td>");
                            tr.append("<td>" + data.Unit + "</td>");
                            tr.append("<td>" + data.Rate + "</td>");

                            var qty = $("#Qty").val();
                            tr.append("<td class='tdQty'>" + qty + "</td>");

                            var amount = data.Rate * qty;

                            tr.append("<td class='tdAmt'>" + amount + "</td>");

                            $('#tblProductsInOrder tbody').append(tr);

                            $("#tblProductsInOrder").css("display", "block");


                            //Total Quantity
                            var tQty = parseInt($("#tQty").html()) + parseInt(qty);
                            $("#tQty").html(tQty);


                            //Total Amount
                            var tAmt = parseFloat($("#tAmt").html()) + parseFloat(amount);
                            $("#tAmt").html(tAmt);


                            //$('#tblProductsInOrder .tdQty').each(function () {
                            //    //var thisQty = $(this).find(".tdQty").html()
                            //    thisQty = $(this).html();
                            //    tQty = tQty + parseInt(thisQty);
                            //});

                        }
                    },
                    error: function () { }
                })
            }
        });

        $("#btnPlaceOrder").click(function () {

            var totalQty = parseInt($("#tQty").html());
            var totalAmt = parseFloat($("#tAmt").html());

            var rowCount = parseInt($("#tblProductsInOrder > tbody > tr").length);

            if ((totalQty < 0 || totalQty == "") || totalAmt == 0 || totalAmt == "" || rowCount == 0 || rowCount == "") {
                alert("Please add products.");
            }
            else {
                var lstOrderDetails = [];

                $('#tblProductsInOrder tbody tr').each(function () {
                    var thisPCode = $(this).find(".tdPCode").html();
                    var thisPQty = $(this).find(".tdQty").html();
                    var thisAmt = $(this).find(".tdAmt").html();

                    lstOrderDetails.push({
                        "ProductCode": thisPCode,
                        "Qty": thisPQty,
                        "Amount": thisAmt
                    });
                });

                var jsonData =
                    {
                        "CustomerID": $("#CustomerID").val(),
                        "lstOrderDetails": lstOrderDetails,
                        "TotalQty": $("#tQty").html(),
                        "TotalAmount": $("#tAmt").html()
                    }

                $.ajax({
                    type: "POST",
                    url: "http://localhost:53405/Orders/SubmitNewOrder",
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(jsonData),
                    cache: false,
                    success: function (data) {
                        alert('Order Added Successfully.');
                    },
                    error: function () { }
                });
            }



        });

        $('#btnUpload').click(function () {
            var custId = parseInt($("#CustomerID").val());

            window.location.href = "http://localhost:53405/Orders/ImportExcel?custId=" + custId + "&orderId=0";
        });
    </script>
}

MicraftSolutions/Views/Orders/Create.cshtml
@model Models.OrdersModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Order</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.Label("Customer Name", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CustomerID, new SelectList(ViewBag.Customers, "ID", "Name"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalQty, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TotalQty, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TotalQty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalAmount, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.TotalAmount, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TotalAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary"  />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    @*<script>
        var date_input = $('#OrderDate'); //our date input has the name "date"
        var container = $('.bootstrap-iso form').length > 0 ? $('.bootstrap-iso form').parent() : "body";
        var options = {
            format: 'dd/mm/yyyy',
            container: container,
            todayHighlight: true,
            autoclose: true,
        };
        date_input.datepicker(options);
    </script>*@
}

MicraftSolutions/Views/Orders/Details.cshtml
@model IEnumerable<Models.OrderDetailsModel>

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        /* Zebra striping */
        tr:nth-of-type(odd) {
            background: #eee;
        }

        th {
            background: #333;
            color: white;
            font-weight: bold;
        }

        td, th {
            padding: 6px;
            border: 1px solid #ccc;
            text-align: left;
        }

    </style>

<h2>Order Details</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OrderID)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ProductCode)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductImage)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.CustomerName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Qty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.TotalQty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalAmount)
        </th>*@        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OrderID)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ProductCode)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            <img class='imgProduct' src='@Html.DisplayFor(modelItem => item.ProductImage)' alt='image'>
            @*@Html.DisplayFor(modelItem => item.ProductImage)*@
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.CustomerName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Qty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.TotalQty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalAmount)
        </td>*@
    </tr>
}
</table>

    <br />

                      <div>
                          @Html.ActionLink("Back to List", "Index")
                      </div>

MicraftSolutions/Views/Orders/ImportExcel.cshtml
@using System.Data;
@{
    ViewBag.Title = "ImportExcel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ImportExcel</h2>
<!--[if !IE]><!-->
<style type="text/css">
        /* Generic Styling, for Desktops/Laptops */
        table {
            width: 100%;
            border-collapse: collapse;
        }
        /* Zebra striping */
        tr:nth-of-type(odd) {
            background: #eee;
        }

        th {
            background: #333;
            color: white;
            font-weight: bold;
        }

        td, th {
            padding: 6px;
            border: 1px solid #ccc;
            text-align: left;
        }
        /*
    Max width before this PARTICULAR table gets nasty
    This query will take effect for any screen smaller than 760px
    and also iPads specifically.
    */
        @@media only screen and (max-width: 760px), (min-device-width: 768px) and (max-device-width: 1024px) {
            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr {
                display: block;
            }
                /* Hide table headers (but not display: none;, for accessibility) */
                thead tr {
                    position: absolute;
                    top: -9999px;
                    left: -9999px;
                }

            tr {
                border: 1px solid #ccc;
            }

            td {
                /* Behave  like a "row" */
                border: none;
                border-bottom: 1px solid #eee;
                position: relative;
                padding-left: 50%;
            }

                td:before {
                    /* Now like a table header */
                    position: absolute;
                    /* Top/left values mimic padding */
                    top: 6px;
                    left: 6px;
                    width: 45%;
                    padding-right: 10px;
                    white-space: nowrap;
                }
                /*
     Label the data
     */
                td:before {
                    content: attr(data-title);
                }
        }
</style>

<!--<![endif]-->
@using (Html.BeginForm("ImportExcel", "Orders", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr><td>Excel file</td><td><input type="file" id="FileUpload1" name="FileUpload1" /></td></tr>
        <tr><td></td><td><input type="submit" class="btn btn-success"  id="Submit" name="Submit" value="Submit" /></td></tr>
    </table>
}

<br/>

<div>
    <table id="">

        @if (ViewBag.Data != null)
        {
            <thead>

                @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                {
                <th>@column.ColumnName.ToUpper()</th>


                }
                </thead>
            if ((ViewBag.Data as System.Data.DataTable).Rows.Count > 0)
            {
                foreach (DataRow dr in (ViewBag.Data as System.Data.DataTable).Rows)
                {

                    <tr>

                        @foreach (DataColumn column in (ViewBag.Data as System.Data.DataTable).Columns)
                        {
                            <td data-title='@column.ColumnName'>

                                @dr[column].ToString()
                            </td>
                        }




                    </tr>

                }

            }
            else
            {
                int count = (ViewBag.Data as System.Data.DataTable).Columns.Count;
                <tr>

                    <td colspan='@count' style="color:red;">

                        No Data Found.
                    </td>



                </tr>

            }

        }
        else
        {
            if (ViewBag.Error != null)
            {
                <tr>
                    <td style="color: red; font-weight: bolder">

                        @(ViewBag.Error != null ? ViewBag.Error.ToString() : "")
                    </td>

                </tr>
            }
        }
        
        @if (ViewBag.Result != null) 
        {
                <tr>
                    <td style="color:green;font-weight:bolder">

                        @(ViewBag.Result != null ? ViewBag.Result.ToString() : "")
                    </td>

                </tr>
        }

    </table>
    
    <br/>

    @Html.ActionLink("Back to List", "Index")

   
</div>  

MicraftSolutions/Views/Orders/Index.cshtml
<h2 style="text-align:center">Orders</h2>

<p style="text-align:right">
    @Html.ActionLink("Add New Order", "AddNewOrder")
</p>


<table class="table" id="tblOrder">
    <thead>
        <tr>
            <th>Order ID</th>
            <th>Order Date</th>
            <th>Customer Name</th>
            <th>Total Quantity</th>
            <th>TotalAmount</th>
            <th>Actions</th>
        </tr>
    </thead>

    <tbody id="tBodyOrder"></tbody>

</table>




@section scripts{
    <script>
        $(document).ready(function () {

            $.ajax({
                type: "GET",
                url: "http://localhost:53405/Orders/GetAllOrders",
                cache: false,
                success: function (data) {
                    //alert(JSON.stringify(data));
                    $('#tBodyOrder').empty();
                    var tr;
                    for (var i = 0; i < data.length; i++) {
                        tr = $('<tr/>');

                        tr.append("<td>" + data[i].OrderID + "</td>");

                        //var date_test = new Date("2011-07-14 11:23:00".replace(/-/g, "/"));
                        //console.log(date_test);

                        var OrderDate = data[i].OrderDate.split(" ")[0];

                        tr.append("<td>" + OrderDate + "</td>");
                        //tr.append("<td>" + data[i].CustomerID + "</td>");
                        tr.append("<td>" + data[i].CustomerName + "</td>");
                        tr.append("<td>" + data[i].TotalQty + "</td>");
                        tr.append("<td>" + data[i].TotalAmount + "</td>");
                        
                        tr.append("<td>"+
                            "<a class='btn btn-success' href='/Orders/Details?orderId=" + data[i].OrderID + "'>Details</a>  "
                            + "<a class='btn btn-success' href='/Orders/Edit?orderId=" + data[i].OrderID + "'>Edit</a>  "
                             + "<a class='btn btn-danger' href='/Orders/Delete?orderId=" + data[i].OrderID + "'>Delete</a>"

                            + "</td>");                        

                        $('#tblOrder tbody').append(tr);
                    }
                },
                error: function () { }
            })

            $('#tblOrder').DataTable(
                {
                    paging: false,
                    ordering: false,
                    searching: false,
                    info: false
                });
        });
    </script>
}